# Generated by Django 3.1.1 on 2021-05-07 04:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('linkedin', models.CharField(blank=True, default='', max_length=254)),
                ('github', models.CharField(blank=True, default='', max_length=254)),
                ('portfolio', models.CharField(blank=True, default='', max_length=254)),
                ('why_join', models.TextField(default='')),
                ('avail_dates', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('pronouns', models.CharField(blank=True, default='', max_length=50)),
                ('bootcamps', models.CharField(blank=True, default='', max_length=50)),
                ('help_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('engineer_skillset', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('engineer_techs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('design_skillset', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('design_techs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('data_sci_skillset', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
