# Generated by Django 3.1.1 on 2021-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210422_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='github',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
