# Generated by Django 3.1.1 on 2021-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='form',
            name='techs',
        ),
        migrations.RemoveField(
            model_name='form',
            name='tell_us',
        ),
        migrations.AddField(
            model_name='form',
            name='avail_dates',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='bootcamps',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='data_sci_skillset',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='design_skillset',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='design_techs',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='engineer_skillset',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='engineer_techs',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='help_with',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='linkedin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='portfolio',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='pronouns',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='why_join',
            field=models.TextField(default=''),
        ),
    ]
